### PR TITLE
Fixed and Improved Gate of the Voidwalkers roguelike Thaumcraft Dungeon

### LINKED ISSUE #23950: Delete Gadomancy Outer Lands (dim id 173) when player leaves it
### Your GTNH Discord Username

_No response_

### Your Pack Version

Daily 406

### Your Proposal

As part of cleanup for Gadomancy's Outer Lands, fully wipe the dimension upon player leaving. Currently, coming back to do another dungeon ends up leaving a bunch of extra garbage left over, which can prevent critical things like the key room or boss room from generating.

### Your Goal

This makes these dungeons easier to spam and grind pearls in

### Your Vision

It makes the dungeon work like it should

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [x] I understand this change request may be rejected due to other community members think it's inappropriate.
- [x] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by thehoblit**
This is a refactor of the Node Manipulator and it's resulting roguelike-ification of Thaumcraft's dungeons for farming Primordial Pearls.

The majority of "changes" are just me reorganizing stuff because of how annoying it was to read.

Fixes:
1. The dungeon should no longer overlap when multiple players have active sessions in multiplayer. (Requires further testing)
2. The multiblock will no longer break itself when it generates a portal.
3. The Redirection Focus is no longer named "Machine" in English.
4. Removed the pedestals as requirements for the multiblock so it doesn't check for  their presence all the time.
5. Moved the break multiblock tracking from a global event tracker to just on the node manipulator.
6. A lot of logic refactors and clean up to make this easier to understand and adjust in the future.

Changes:
1. Added sound to the multiblock's lightning effects.
2. Made the Node Redirection spend it's entire pool instead of pointlessly less.
3. Added an exit portal spawn to the boss room upon completion. It already spawned one at the initial spawn location, but that would never get used as you can just re-log to quickly exit the dungeon.
4. Added a timer for dungeon completions, tracking high scores. Very Roguelike.
5. Made the dungeon smaller on average. Faster runs, more Primordial Pearls.

The main question is balance. I am advocating to buff this as an active method of farming Pearls. Current Thaumcraft dungeons spawn with a length and width of either 11-23 or 15-31 depending on how world generation pans out. In this PR I have changed the size from 17-21 to 12-16, following the bottom range of natural Thaumcraft generation. Based on my testing, this should average out to about 5 minutes per run with good path finding and route tracking. Basically, running a DFS in real time as fast as you can run.

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23950

### CODE REVIEW

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileOverrideEldritchLock.java [hunk 1]
```diff
@@ -20,35 +22,56 @@ public class TileOverrideEldritchLock extends TileEldritchLock {
...
+                        centerx = cx + a;
+                        centerz = cz + b;
                     }
-                    return;
                 }
             }
-        }
 
-        super.updateEntity();
+            centerx = centerx * 16 + 16;
```
Comment (Luca-Guettinger) [inline src/main/java/makeo/gadomancy/common/blocks/tiles/TileOverrideEldritchLock.java:71]: Boss portal coordinate is off. `centerx * 16 + 16` places the portal at block 0 of the next chunk, not centered in the boss room chunk. Compare with TCMazeSession.findPortal which correctly uses `chunk.x * 16 + 8`. Same for centerz.

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java [hunk 2]
```diff
@@ -480,86 +499,116 @@ public void breakMultiblock() {
...
+    }
+
+    private boolean shouldSkipOnForm(MultiblockHelper.BlockInfo info) {
+        return info.block == RegisteredBlocks.blockNode || info.block == Blocks.air
+                || info.block == RegisteredBlocks.blockNodeManipulator
+                || (info.block == RegisteredBlocks.blockStoneMachine
+                        && (info.meta == 0 || info.meta == 1 || info.meta == 3));
+    }
+
+    private boolean shouldSkipOnBreak(MultiblockHelper.BlockInfo info) {
```
Comment (Luca-Guettinger) [inline src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java]: shouldSkipOnForm and shouldSkipOnBreak have identical bodies. Could be a single method unless there's a planned difference.

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java [hunk 3]
```diff
@@ -41,321 +40,330 @@
...
-                            && te instanceof TilePedestal
-                            && (!checkForEyes || this.checkTile((TilePedestal) te))) {
-                        validPedestalsFound++;
-                        this.bufferedCCPedestals.add(new ChunkCoordinates(itX, itY, itZ));
-                        if (validPedestalsFound >= 4) {
-                            break labelIt;
-                        }
-                        continue labelZ;
-                    }
+    private boolean isMultiblockPresent() {
```
Comment (Luca-Guettinger) [inline src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java:113]: Switching on a null multiblockType here will NPE. Can happen if breakMultiblock() sets multiblockType = null before the caller sets isMultiblock = false, or on NBT load from an older save. Either null-check before the switch or just return false at the top if multiblockType is null.

File: src/main/java/makeo/gadomancy/common/utils/world/TCMazeHandler.java [hunk 4]
```diff
@@ -66,14 +79,15 @@ public static void closeAllSessionsAndCleanup() {
...
+        WorldServer world = DimensionManager.getWorld(ModConfig.dimOuterId);
+        if (world != null) {
+            if (!world.levelSaving) world.levelSaving = true;
 
             WorldServer out = MinecraftServer.getServer().worldServerForDimension(0);
-            List playerObjects = w.playerEntities;
-            for (int i = 0; i < playerObjects.size(); i++) {
-                EntityPlayer player = (EntityPlayer) playerObjects.get(i);
+            // Raw list and regular for loop to not cause ConcurrentModificationException when relogging with an active
+            // session. I don't know enough java to know why.
```
Comment (Luca-Guettinger) [inline src/main/java/makeo/gadomancy/common/utils/world/TCMazeHandler.java]: The comment could be more helpful. The CME happens because teleporting a player modifies world.playerEntities during iteration. Copying the list first gives a stable snapshot to iterate over. Something like "Copy to avoid CME when teleporting modifies the player list" would explain it better.

**Review by Luca-Guettinger — DISMISSED** [review]
1 bug in the boss portal placement (off by 8 blocks, lands in the wrong chunk), plus 3 minor nits on code dedup and defensiveness.

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileOverrideEldritchLock.java (hunk 1 above)
Comment (thehoblit) [reply src/main/java/makeo/gadomancy/common/blocks/tiles/TileOverrideEldritchLock.java:71]: These coordinates are correct because the dungeon room is awkwardly sized, and the corner of the door chunk is the center of the room. I took the spawning math from where thaum spawns the bosses in the mazeHandler.

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java (hunk 2 above)
Comment (thehoblit) [reply src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java]: good catch, I don't know why intellij didn't see this.

File: src/main/java/makeo/gadomancy/common/utils/world/TCMazeHandler.java (hunk 4 above)
Comment (thehoblit) [reply src/main/java/makeo/gadomancy/common/utils/world/TCMazeHandler.java]: I forgot to change that after asking in the discord lmao, thanks.

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileOverrideEldritchLock.java (hunk 1 above)
Comment (Luca-Guettinger) [reply src/main/java/makeo/gadomancy/common/blocks/tiles/TileOverrideEldritchLock.java:71]: alright, thats cursed but then its fine

File: src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java (hunk 3 above)
Comment (thehoblit) [reply src/main/java/makeo/gadomancy/common/blocks/tiles/TileNodeManipulator.java:113]: added the early return

**Comment by Luca-Guettinger** [comment]
Code Looks good to me, someone else should look at balancing.

**Review by koolkrafter5 — APPROVED** [review]
Balancing looks good since this is a more active way to farm pearls

**Review by Luca-Guettinger — APPROVED** [review]
