### PR TITLE
Cleanup event classes more and fix dedicated server crash

### LINKED ISSUE #23000: TC Golem Rendering Crash
### Your GTNH Discord Username

Redderpears

### Your Pack Version

2.9.x daily 296

### Your Server

private server

### Java Version

Java 25

### Type of Server

Vanilla Forge

### Your Actions

1. spin up a regular server + client install of daily 296
2. join and place any TC golem
3. immediate client crash, continues to crash when rejoining

This crash also occurs if loading a golem that is already placed. Does not work in a single player world.

sadly no one in the discord was willing to crash their server for me :(

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/24319299/fml-client-latest.log)
https://mclo.gs/kWk4MK8

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by Alexdoru**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23000

introduced by https://github.com/GTNewHorizons/Gadomancy/pull/44

### CODE REVIEW

File: src/main/java/makeo/gadomancy/client/events/RenderEventHandler.java [hunk 1]
```diff
@@ -60,21 +59,39 @@
...
+            buf = null;
+        }
+        obj = buf;
+    }
+
+    private final REHWandHandler WAND_HANDLER = new REHWandHandler();
+    private final FakeArchitectItem ARCHITECT_ITEM = new FakeArchitectItem();
     private Object oldGolemblurb;
     private int blurbId;
+    private int dList = -1;
```
Comment (Nikolay-Sitnikov) [inline src/main/java/makeo/gadomancy/client/events/RenderEventHandler.java:90]: Is there any chance that `dList` might get forgotten without freeing the GL display lists linked to it? I don't think so, since there's no code to unbind the event handler, but that probably deserves a comment just in case.

File: src/main/java/makeo/gadomancy/common/CommonProxy.java [hunk 2]
```diff
@@ -72,6 +73,8 @@ public void initalize() {
         RegisteredEntities.init();
         DimensionManager.registerProviderType(ModConfig.dimOuterId, WorldProviderTCEldrich.class, true);
         DimensionManager.registerDimension(ModConfig.dimOuterId, ModConfig.dimOuterId);
+        FMLCommonHandler.instance().bus().register(new EventHandlerNetwork());
+        MinecraftForge.EVENT_BUS.register(new EventHandlerGolem());
```
Comment (Nikolay-Sitnikov) [inline src/main/java/makeo/gadomancy/common/CommonProxy.java:77]: You may want to mention that these specific event handlers are stateless to explain why these don't get unregistered.

**Review by Nikolay-Sitnikov — APPROVED** [review]
Other than the small comments I left, this should be all fine.

File: src/main/java/makeo/gadomancy/common/CommonProxy.java (hunk 2 above)
Comment (Alexdoru) [reply src/main/java/makeo/gadomancy/common/CommonProxy.java:77]: it's obvious when you open the file

File: src/main/java/makeo/gadomancy/client/events/RenderEventHandler.java (hunk 1 above)
Comment (Alexdoru) [reply src/main/java/makeo/gadomancy/client/events/RenderEventHandler.java:90]: idk it's the same as the original code
